#!/usr/bin/env python


import src.pdb_parser
import src.cli


def main():
    args = src.cli.parse_args()

    #set up class for complex

    complex = src.pdb_parser.Complex(args.infile, args.complex_1, args.complex_2, verbose=True,
                                     distance=args.distance)
    if args.command == "asa":
        complex.create_sub_pdbs()
        complex.complex_sasa()
    if args.command == "sc":
        complex.sc()


if __name__ == "__main__":
    main()