#!/usr/bin/env python

from scasa import scasa
from scasa import cli


def main():
    args = cli.parse_args()

    # set up class for complex

    pdb_complex = scasa.Complex(args.infile, args.complex_1, args.complex_2, verbose=args.verbose,
                            distance=args.distance, weight=args.weight)
    if args.command == "asa":
        pdb_complex.create_sub_pdbs()
        pdb_complex.complex_sasa()
    if args.command == "sc":
        pdb_complex.sc()


if __name__ == "__main__":
    main()
